### ISSUE TITLE
cli is not working

### ISSUE THREAD

**Issue by omry** [nkashy1/command-line-yoga#1]
Hi, I just watched the recording from Pyninsula 25, and I wanted to show you a new project I am working on using your example as a base.

Unfortunately it's not quite working with Python 3.7:
```
$ python --version
Python 3.7.6
```

Can you make sure cli.py is runnable (ideally with a proper setup.py to pip install -e)?
There are some issues there:

```
$ python yoga/cli.py 
Traceback (most recent call last):
  File "yoga/cli.py", line 9, in <module>
    from .index import index_document
ImportError: attempted relative import with no known parent package
```

after fixing the import to absolute (not sure why it's needed): 
`from yoga.index import index_document`

```
$ PYTHONPATH=. python yoga/cli.py 
Traceback (most recent call last):
  File "yoga/cli.py", line 88, in <module>
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```
